[2024-11-09T22:31:39.604+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-09T22:31:39.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_Data_ETL.initialize_target_table manual__2024-11-09T22:31:38.524078+00:00 [queued]>
[2024-11-09T22:31:39.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_Data_ETL.initialize_target_table manual__2024-11-09T22:31:38.524078+00:00 [queued]>
[2024-11-09T22:31:39.622+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-09T22:31:39.628+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): initialize_target_table> on 2024-11-09 22:31:38.524078+00:00
[2024-11-09T22:31:39.633+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1528) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-09T22:31:39.634+0000] {standard_task_runner.py:63} INFO - Started process 1539 to run task
[2024-11-09T22:31:39.634+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_Data_ETL', 'initialize_target_table', 'manual__2024-11-09T22:31:38.524078+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/FinanceDataAnalytics_ETL_Pair9.ipynb.py', '--cfg-path', '/tmp/tmpicajwnr8']
[2024-11-09T22:31:39.635+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask initialize_target_table
[2024-11-09T22:31:39.659+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_Data_ETL.initialize_target_table manual__2024-11-09T22:31:38.524078+00:00 [running]> on host c8883bd7101d
[2024-11-09T22:31:39.697+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu,pranav.raveendran@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Pair 9' AIRFLOW_CTX_DAG_ID='Stock_Data_ETL' AIRFLOW_CTX_TASK_ID='initialize_target_table' AIRFLOW_CTX_EXECUTION_DATE='2024-11-09T22:31:38.524078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-09T22:31:38.524078+00:00'
[2024-11-09T22:31:39.698+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-09T22:31:39.703+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-09T22:31:39.704+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-09T22:31:39.705+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-09T22:31:40.604+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-09T22:31:40.607+0000] {logging_mixin.py:188} INFO - Target Table Initialized and Ready to Store Data from ETL
[2024-11-09T22:31:40.607+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-09T22:31:40.608+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-09T22:31:40.615+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Stock_Data_ETL, task_id=initialize_target_table, run_id=manual__2024-11-09T22:31:38.524078+00:00, execution_date=20241109T223138, start_date=20241109T223139, end_date=20241109T223140
[2024-11-09T22:31:40.644+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-09T22:31:40.658+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-09T22:31:40.661+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
