[2024-11-10T06:25:24.382+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T06:25:24.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_Prediction.predict manual__2024-11-10T06:23:27.835219+00:00 [queued]>
[2024-11-10T06:25:24.398+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_Prediction.predict manual__2024-11-10T06:23:27.835219+00:00 [queued]>
[2024-11-10T06:25:24.398+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-10T06:25:24.403+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): predict> on 2024-11-10 06:23:27.835219+00:00
[2024-11-10T06:25:24.407+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_Prediction', 'predict', 'manual__2024-11-10T06:23:27.835219+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/FinanceDataAnalytics_Prediction_Pair9.ipynb.py', '--cfg-path', '/tmp/tmpvfuy5d4f']
[2024-11-10T06:25:24.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=531) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-10T06:25:24.409+0000] {standard_task_runner.py:91} INFO - Job 127: Subtask predict
[2024-11-10T06:25:24.409+0000] {standard_task_runner.py:63} INFO - Started process 534 to run task
[2024-11-10T06:25:24.429+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_Prediction.predict manual__2024-11-10T06:23:27.835219+00:00 [running]> on host 2538ecb7b4d3
[2024-11-10T06:25:24.467+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Pair 9' AIRFLOW_CTX_DAG_ID='Stock_Prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T06:23:27.835219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T06:23:27.835219+00:00'
[2024-11-10T06:25:24.467+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T06:25:24.472+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-10T06:25:24.473+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-10T06:25:24.473+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-10T06:25:43.849+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-10T06:25:44.767+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-10T06:25:44.768+0000] {connection.py:762} INFO - closed
[2024-11-10T06:25:44.808+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-10T06:25:44.863+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-10T06:25:44.864+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T06:25:44.870+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Stock_Prediction, task_id=predict, run_id=manual__2024-11-10T06:23:27.835219+00:00, execution_date=20241110T062327, start_date=20241110T062524, end_date=20241110T062544
[2024-11-10T06:25:44.901+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-10T06:25:44.908+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T06:25:44.909+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
