[2024-11-12T21:30:05.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T21:30:05.126+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_Data_ETL.load_stock_data scheduled__2024-11-11T21:30:00+00:00 [queued]>
[2024-11-12T21:30:05.129+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_Data_ETL.load_stock_data scheduled__2024-11-11T21:30:00+00:00 [queued]>
[2024-11-12T21:30:05.129+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T21:30:05.134+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_stock_data> on 2024-11-11 21:30:00+00:00
[2024-11-12T21:30:05.138+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=32017) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T21:30:05.139+0000] {standard_task_runner.py:63} INFO - Started process 32020 to run task
[2024-11-12T21:30:05.138+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_Data_ETL', 'load_stock_data', 'scheduled__2024-11-11T21:30:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/FinanceDataAnalytics_ETL_Pair9.ipynb.py', '--cfg-path', '/tmp/tmpmvu5vc0j']
[2024-11-12T21:30:05.140+0000] {standard_task_runner.py:91} INFO - Job 165: Subtask load_stock_data
[2024-11-12T21:30:05.159+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_Data_ETL.load_stock_data scheduled__2024-11-11T21:30:00+00:00 [running]> on host 2538ecb7b4d3
[2024-11-12T21:30:05.228+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Pair 9' AIRFLOW_CTX_DAG_ID='Stock_Data_ETL' AIRFLOW_CTX_TASK_ID='load_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T21:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T21:30:00+00:00'
[2024-11-12T21:30:05.228+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T21:30:05.235+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-12T21:30:05.236+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-12T21:30:05.236+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-12T21:30:06.214+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-12T21:30:06.769+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-12T21:30:06.770+0000] {logging_mixin.py:188} INFO - Target Table Initialized and Ready to Store Data from ETL
[2024-11-12T21:30:06.770+0000] {logging_mixin.py:188} INFO - Loading Apple stock data...
[2024-11-12T21:30:56.710+0000] {logging_mixin.py:188} INFO - Loading Nvidia stock data...
[2024-11-12T21:31:41.802+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-12T21:31:41.803+0000] {logging_mixin.py:188} INFO - Data load complete for Apple and Nvidia stocks.
[2024-11-12T21:31:41.803+0000] {connection.py:762} INFO - closed
[2024-11-12T21:31:41.852+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-12T21:31:41.907+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T21:31:41.907+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T21:31:41.919+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Stock_Data_ETL, task_id=load_stock_data, run_id=scheduled__2024-11-11T21:30:00+00:00, execution_date=20241111T213000, start_date=20241112T213005, end_date=20241112T213141
[2024-11-12T21:31:42.204+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-12T21:31:42.220+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-12T21:31:42.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
